### PR TITLE
Application Instances: Remove Application > Remote Instances list

### LINKED ISSUE #1825: Application Instances: Flash of team devices on application page
> When viewing an application that has no devices attached, Nick sees one flash, then disappears (seems to suggest it was attached to application at one point, and has since been removed?)

Related to https://github.com/flowforge/flowforge/issues/1824

### LINKED ISSUE #1826: UX Onboarding Flow Review
### Description

Reviewing of the PostHog CTA funnels and take relevant design actions

### Epic/Story

_No response_

### PR DESCRIPTION
**Pull request by Pezmc**
## Description

Removes the remote instances list from the Application > Instances page entirely.

### Before

Screenshot 2023-03-14 at 16 14 15

**Of note:** This explanation dialog **no longer exists** and has no replacement @joepavitt 

Screenshot 2023-03-14 at 16 14 08

#### Application > Instances
Screenshot 2023-03-14 at 16 14 28

#### New loading state for Application pages
Screenshot 2023-03-14 at 15 56 46

#### Improved loading state for Instance pages
Screenshot 2023-03-14 at 16 16 46

## Related Issue(s)

Fix #1825
Fix #1826 

## Checklist

 - [x] I have read the [contribution guidelines](https://github.com/flowforge/flowforge/blob/main/CONTRIBUTING.md)
 - [-] Suitable unit/system level tests have been added and they pass
 - [-] Documentation has been updated
    - [ ] Upgrade instructions
    - [ ] Configuration details
    - [ ] Concepts
 - [-] Changes `flowforge.yml`?
    - [ ] Issue/PR raised on `flowforge/helm` to update ConfigMap Template
    - [ ] Issue/PR raised on `flowforge/CloudProject` to update values for Staging/Production

## Labels

 - [ ] Backport needed? -> add the `backport` label
 - [ ] Includes a DB migration? -> add the `area:migration` label

### CODE REVIEW

**Comment by joepavitt** [comment]
re: the dialog now being removed, worth moving this to be accesible on the Instance > Devices table?

**Comment by Pezmc** [comment]
@joepavitt If you have a proposal as to where, it doesn't fit well with the current shared header design:

Screenshot 2023-03-14 at 16 53 31

**Comment by joepavitt** [comment]
It does not - right you are. I'll have a play when renaming the "Remote Instances" option.

**Comment by joepavitt** [comment]
@Pezmc this claims to have fixed #1826 - which isn't related, can you update to the correct issue please, and I'll reopen #1826

**Pull request merged**
