### PR TITLE
Adds differentiation in messaging between debit/credit amounts

### LINKED ISSUE #2416: Mismatched credit text / values when money is owed
When a users credit value is positive (i.e. owes) the UI does not handle this correctly in all places.

image

Issue was discovered while developing #2404 and is not something that needs fixing today since we currently do not support moneys owed.

_Originally posted by @Steve-Mcl in https://github.com/flowforge/flowforge/issues/2404#issuecomment-1621475907_

### PR DESCRIPTION
**Pull request by joepavitt**
## Description

Update messaging to be a function of whether Stripe credit is +ve/-ve.

When in credit:

Screenshot 2023-07-27 at 13 55 34

When in debit:

Screenshot 2023-07-27 at 13 55 02

## Related Issue(s)

Closes #2416 

## Checklist

 - [x] I have read the [contribution guidelines](https://github.com/flowforge/flowforge/blob/main/CONTRIBUTING.md)
 - [x] Suitable unit/system level tests have been added and they pass

### CODE REVIEW

**Comment by Steve-Mcl** [comment]
Looks good.

one question, what is shown when there is zero credit/debit?  Are elements hidden or does it state $0 debit? or $0 credit?

**Comment by joepavitt** [comment]
No credit/debit:

Screenshot 2023-07-27 at 14 07 09

**Review by Steve-Mcl — APPROVED** [review]
Approved. But one question I have is do we need a banner for debit balance? 🤔 

Probably not - but ...

Happy to merge as is Joe - will wait your signal.

**Comment by joepavitt** [comment]
I don't think so at this stage. I suspect, if someone owes us money, we'll just be taking it from them anyway. If situation arises and we need that banner, then, new issue. Out of scope of the original issue raised here.

**Comment by Pezmc** [comment]
I believe this PR introduced a bug when the user doesn't owe or has credit anything for anything:
 
Screenshot 2023-08-07 at 12 07 12

Tracking in https://github.com/flowforge/flowforge/issues/2562

**Pull request merged**
