### PR TITLE
Add "User Interview" prompts

### LINKED ISSUE #1828: In-App User Feedback Prompts
### Epic

_No response_

### Description

Inspired by: https://posthog.com/blog/10x-engineers-do-user-interviews

PH saw a 3% - 15% improvement in getting user feedback by using targeted user lists and PostHog feature flags, this _should_ be a fairly quick win feature we could experiment with a few users to see what engagement looks like.

### Which customers would this be availble to

None

### Acceptance Criteria

_No response_

### PR DESCRIPTION
**Pull request by joepavitt**
## Description

Screenshot 2023-03-30 at 13 01 50

Enable PostHog Apps such that the Interviewer app can generate the popup. All configuration done within PotHog to control:

- Criteria a user must fit in order to qualify for a popup
- What the popup says
- % of users in the given criteria that will see the message
- How many days before a user can see a popup again once they've actioned (Closed or Booked)

### Update

See https://github.com/flowforge/flowforge/pull/1894#issuecomment-1496535182

- No longer using the default PostHog App to provide the popup (but still using it for the config options) as we are using our own styled (and positioned) popup

## Related Issue(s)

Closes #1828 

## Checklist

 - [x] I have read the [contribution guidelines](https://github.com/flowforge/flowforge/blob/main/CONTRIBUTING.md)
 - [-] Suitable unit/system level tests have been added and they pass
 - [-] Documentation has been updated
    - [-] Upgrade instructions
    - [-] Configuration details
    - [-] Concepts
 - [-] Changes `flowforge.yml`?
    - [-] Issue/PR raised on `flowforge/helm` to update ConfigMap Template
    - [-] Issue/PR raised on `flowforge/CloudProject` to update values for Staging/Production

## Labels

 - [-] Backport needed? -> add the `backport` label
 - [-] Includes a DB migration? -> add the `area:migration` label

### CODE REVIEW

**Comment by joepavitt** [comment]
I was hoping to have the popup appear in the top-right, but that would require us to build a custom popup and isn't worth the hassle at the moment.

**Comment by joepavitt** [comment]
Had a call with Luke, Product Manager for the Interview work in PostHog and he took onboard some feedback, that he said they'd be able to implement in the next few weeks. Won't require any code changes, all PostHog-side, but will give.us a little more control on positioning and styling.

**Comment by knolleary** [comment]
How well does this co-exist with the hubspot inline chat?

image

**Comment by joepavitt** [comment]
ooh - very good point - I don't have that enabled localy, let me configure

**Comment by joepavitt** [comment]
Well that's less than ideal:

Screenshot 2023-03-31 at 09 41 26

**Comment by joepavitt** [comment]
PostHog doesn't allow for moving that pop-up at the moment, unless we build our own custom popup (is plausible but half a day, to a days work).

Not sure we have much control over the HubSpot one either do we, i.e. we can't delay it appearing _if_ the PostHog widget is present, etc)

**Comment by joepavitt** [comment]
went ahead and built our own popup instead, was fairly straight forward to implement and can be configured via the feature flag `payload` instead of the PostHog "User Interview" app, currently we can configure:

| key | example | description |
|---|---|---|
|`invitationTitle`| Help us improve FlowForge | Text shown as the primary title of the popup
|`invitationBody`| We'd love to hear more about how you're using FlowForge, and get your feedback on a short call. | Body of the popup to provide more detail on why it's been shown.
|`closeText`| No Thanks | Text to populate the dismiss/close button. Defaults to `Close`
|`bookText`| Book Now | Text to populate the primary/book button. Defaults to `Book Now`
|`bookingLink`| `https://calendly.com/<user>/<event>` | URL pointing to a Calendly invite such that a user can book a meeting slot.

**Review by Pezmc — APPROVED** [review]
@joepavitt Ran me though setting this up locally, we did some extra click testing and confirmed all is working (minus two small edge cases fixed above)!

**Pull request merged**
