### PR TITLE
Toast Alerts

### PR DESCRIPTION
**Pull request by joepavitt**
Dependent upon: https://github.com/flowforge/forge-ui-components/pull/24

first half of https://github.com/flowforge/flowforge/issues/515 (see this issue for a screen recording demo)

### CODE REVIEW

**Comment by joepavitt** [comment]
Expecting build to fail at the moment (PR still in draft state) as I'm still referencing my local forge-ui-components in the package json

**Comment by knolleary** [comment]
The basic mechanism looks good. Not 100% on the appearance yet - but we can refine later.

Would be good to capture some docs on how to use it and guidelines on *when* to use it. I know there are a bunch of actions being added in my various PRs that'll merge over the coming days before 0.7 that will need updating to incorporate it.

**Comment by joepavitt** [comment]
Thanks @knolleary  - actually agree on the appearance. I went for the generic toast appearance just to get something in, but it does feel out of place with the rest of the UI which I find a lot cleaner/slicker. Will happily iterate.

All available in Figma if you did want to play yourself too.

**Comment by joepavitt** [comment]
RE: Docs - I have been thinking quite a bit about this, and in particular, _where_ that should live. I feel like a natural home is actually the handbook under a "Design Language" section? Doesn't quite feel right in `forge-ui-components` as it's about more than just the raw Vue components.

**Pull request merged**
