### PR TITLE
Update sequelize 

### PR DESCRIPTION
**Pull request by Pezmc**
As part of updating moment-timezone above 0.5.34

### CODE REVIEW

**Review by Steve-Mcl — APPROVED** [review]

**Comment by Steve-Mcl** [comment]
bah - conflicts @Pezmc

**Comment by Pezmc** [comment]
On it

**Comment by Pezmc** [comment]
Rebased on top of `main`

**Comment by Steve-Mcl** [comment]
@Pezmc I realise this is the familiar "limit Allocation failed" error, but as this is related to DB stuff, I think we should try to get at leasy 1 pass on PG tests?

**Pull request merged**
