### PR TITLE
Add httpNodeAuth settings

### PR DESCRIPTION
**Pull request by hardillb**
Allows the setting of a single username/password in the template

Fixes #https://github.com/flowforge/flowforge/issues/578

Requires https://github.com/flowforge/flowforge-nr-launcher/pull/64

Screenshot from 2022-09-09 14-03-17

### CODE REVIEW

**Comment by hardillb** [comment]
Does the password bcrypt in page so only the hash is ever sent to the backend and stored in the database

**Comment by hardillb** [comment]
@knolleary I have pushed what might be a slightly naive fix for the password getting overwitten on any other change to the template.

**Comment by knolleary** [comment]
I've reworked how passwords are handled in template settings.

We now hash them in the backend before they are stored. We never return the value in the api - we return a boolean to indicate if a non-blank value exists.

The UI then does the Right Thing to show a placeholder or not.

I have verified the settings are applied properly by the launcher - and that the values can be overridden in the project.

There is one PR to come against the launcher to avoid righting blank settings into httpNodeAuth.

**Comment by knolleary** [comment]
Huh - @hardillb as the person who raised this PR originally, it will now let me add you as a reviewer (which is why I tried unassigning it from you first...). Please take a look.

**Comment by hardillb** [comment]
Yep, was already looking, got confused for a second as to why there was no change to package.json to remove the `bcryptjs`, but makes sense now

**Comment by hardillb** [comment]
Code looks OK, but 2 of the UI tests are with something to do with httpNodeAuth

**Comment by hardillb** [comment]
All the tests pass locally, so I'm happy to merge this (and we need to set aside some time next sprint to fix the postgres tests and work out what's happening here)

**Pull request merged**
