### PR TITLE
added additional steps to setup dev environemnt

### PR DESCRIPTION
**Pull request by sammachin**

### CODE REVIEW

**Comment by hardillb** [comment]
Looks good, but do you want to add a bit about creating starting stack?

**Comment by sammachin** [comment]
Do you mean with `npm run install-stack --vers=2.2.2` or via the GUI?

**Comment by hardillb** [comment]
The command line stuff, The gui forces you to create a stack, but the setup in `var/stacks` needs to be done first

**Comment by sammachin** [comment]
added

**Review by hardillb — APPROVED** [review]

**Pull request merged**
