### PR TITLE
Show Team ID in Team > Settings > General

### PR DESCRIPTION
**Pull request by joepavitt**
- Also cleaned up an excessive object structure in there for `editing` state

### CODE REVIEW

**Review by Pezmc — APPROVED** [review]

**Review by Pezmc — CHANGES_REQUESTED** [review]
Does data.editing not need to be updated?

**Comment by joepavitt** [comment]
> Does data.editing not need to be updated?

right you are, although it does work without the change.

**Comment by joepavitt** [comment]
had some other local changes that hadn't pushed too - woops. Thanks for flagging.

**Review by Pezmc — APPROVED** [review]
That looks better! 👯

**Pull request merged**
