### PR TITLE
Add subtitles, popup and info around Applications/Instances

### LINKED ISSUE #1995: Application/Instances views missing info popup dialog and header description
### Current Behavior

Devices view has the ℹ️ icon and description of the view:

image

Applications and Instances view do not:

image

image

### Expected Behavior

_No response_

### Steps To Reproduce

_No response_

### Environment

- FlowForge version:
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

### PR DESCRIPTION
**Pull request by Steve-Mcl**
closes #1995

## Description

* Add missing subtitles
* Add info button and popup
* Ensure texts align with current implementation

image

image

## Related Issue(s)

#1995 

## Checklist

 - [x] I have read the [contribution guidelines](https://github.com/flowforge/flowforge/blob/main/CONTRIBUTING.md)
 - [ ] Suitable unit/system level tests have been added and they pass 
 - [x] Documentation has been updated
    - [ ] Upgrade instructions
    - [ ] Configuration details
    - [ ] Concepts
 - [ ] Changes `flowforge.yml`?
    - [ ] Issue/PR raised on `flowforge/helm` to update ConfigMap Template
    - [ ] Issue/PR raised on `flowforge/CloudProject` to update values for Staging/Production

## Labels

 - [ ] Backport needed? -> add the `backport` label
 - [ ] Includes a DB migration? -> add the `area:migration` label

### CODE REVIEW

**Comment by Steve-Mcl** [comment]
@knolleary PR in draft as I suspect UI folk may want to review/adjust icons

Feel free to switch to release if necessary.

**Comment by knolleary** [comment]
@Steve-Mcl if you want it to be reviewed, then mark it ready and add the appropriate people as reviewers. As it stands there's no indication there's any action outstanding with anyone other than you.

**Comment by Steve-Mcl** [comment]
> I just need to color them because the ones we have are all gray, could this wait until tomorrow morning?

of course.

**Comment by Yndira-FlowForge** [comment]
Hi @Steve-Mcl the images you need are in the [drive](https://drive.google.com/drive/folders/12CVebPePLnM-HGmbj2az89-EcylDAD1x?usp=sharing), these are the ones you should use:
Screenshot 2023-05-25 at 12 15 14

**Comment by Yndira-FlowForge** [comment]
@Steve-Mcl just added two more, in case you want to replace the one we have in snapshots now and if we need one for pipelines too.
Screenshot 2023-05-26 at 13 25 43

**Comment by Steve-Mcl** [comment]
@Yndira-FlowForge I can certainly include them when I get back to this PR (later today or Monday) - are you/Joe happy for me to add the update the pictures in this PR (not to tenuous in regards to the original issue?)

**Comment by joepavitt** [comment]
@Steve-Mcl what's the status here? Any particular reason it's still in draft?

**Comment by Steve-Mcl** [comment]
@joepavitt switched back to draft so this doesn't get inadvertently merged without updating the popup graphics with those  kindly provided by Yndira.

And the only reason I have not yet come back to this is because my dev-env is kinda a mess while I develop another feature. 

Should be updated before end of today Joe & I will switch back to release.


---

in short, I need to add the new graphics: 

> Hi @Steve-Mcl the images you need are in the [drive](https://drive.google.com/drive/folders/12CVebPePLnM-HGmbj2az89-EcylDAD1x?usp=sharing), these are the ones you should use:
> Screenshot 2023-05-25 at 12 15 14

...  and apply them to the popups to finish this off.

**Comment by joepavitt** [comment]
Thanks Steve - I'll take this and update the images

**Comment by joepavitt** [comment]
failing tests are out of scope for this PR, they're fixed in: https://github.com/flowforge/flowforge/pull/2195/files

**Review by joepavitt — APPROVED** [review]

**Pull request merged**
