### PR TITLE
make Instance and application  names in delete popup  easily selectable

### LINKED ISSUE #2267: Instance names in delete popup not easily selectable
### Current Behavior

double clicking on the instance name used to select just the name, this made copy/paste to the Name box a lot quicker/easier when deleting instances.

I'm sure this component is probably reused for deleting other things that require confirmation.

Screenshot from 2023-06-09 14-55-02

Looks like the `<code>` tag used to have the `class='block'`

### Expected Behavior

Double click on the name selects just the name, not the whole line.

### Steps To Reproduce

Try to delete and instance
double click on the instance name &lt;code&gt; section

### Environment

- FlowForge version: 1.8.0
- Node.js version:  16.x
- npm version: 8.x
- Platform/OS: NA
- Browser: Chrome

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

### PR DESCRIPTION
**Pull request by sumitshinde-84**
## Description

 
i have used ```flex```  on parent  instead of  using ```block``` because if we use only ```block```  it will select easily instance and application name but code block   will start from new line like below 

[
flowforge2
](url)

and popup Ui will  not broke if we use ```flex``` like below

flowforge3

## Related Issue(s)
closes #2267 

## Checklist

 - [x] I have read the [contribution guidelines](https://github.com/flowforge/flowforge/blob/main/CONTRIBUTING.md)
 - [ ] Suitable unit/system level tests have been added and they pass 
 - [ ] Documentation has been updated
    - [ ] Upgrade instructions
    - [ ] Configuration details
    - [ ] Concepts
 - [ ] Changes `flowforge.yml`?
    - [ ] Issue/PR raised on `flowforge/helm` to update ConfigMap Template
    - [ ] Issue/PR raised on `flowforge/CloudProject` to update values for Staging/Production

## Labels

 - [ ] Backport needed? -> add the `backport` label
 - [ ] Includes a DB migration? -> add the `area:migration` label

### CODE REVIEW

**Comment by Pezmc** [comment]
Hi @sumitshinde-84, thank you for your contribution! I can see click testing locally that the experience is slightly improved, but on my machine it requires a _tripple_ click, I'm going to tag someone to check if that's what they were looking for.

@Steve-Mcl Was the original request to enable double clicking to select instance name? This change appears to allow triple clicking (at least checking on macOS), can you see how it behaves locally for you?

https://github.com/flowforge/flowforge/assets/507155/24d913e3-19ce-48cf-931e-13544a0a3f8d

**Comment by Steve-Mcl** [comment]
@Pezmc triple click is what I used to do and #1962 removed this. 

I had pointed it out here: https://github.com/flowforge/flowforge/pull/1962#issuecomment-1505334291 (but it was already merged and I was not the reviewer. 

You did suggest (in the next comment) that you might add click to copy - which would be sweet but triple click is something I am personally very familiar with so I'm fine either way Pez. 


Ps, I did try this change earlier (I was intrigued as to why it worked) and it did work, but I did notice some odd text alignment going on (possibly down to our styles?)

**Comment by hardillb** [comment]
Tripple click (for names with a `-`) double for names without works for me.

**Comment by sumitshinde-84** [comment]
@hardillb can i  increase  some js lines of  code so i can fix this issue .

**Review by hardillb — APPROVED** [review]

**Pull request merged**
