### PR TITLE
Add FF_SNAPSHOT_ID to devices

### PR DESCRIPTION
**Pull request by knolleary**
Closes https://github.com/flowforge/flowforge-device-agent/issues/94

## Description

This adds `FF_SNAPSHOT_ID` to the env passed down to devices. This is set to the id of the targetSnapshot for the device.

## Checklist

 - [x] I have read the [contribution guidelines](https://github.com/flowforge/flowforge/blob/main/CONTRIBUTING.md)
 - [x] Suitable unit/system level tests have been added and they pass 
 - [x] Documentation has been updated

### CODE REVIEW

**Comment by Steve-Mcl** [comment]
Nick, should we not include the snapshot name and description? Similar to how the device name and type are be used in flows to "do something else" I can foresee similar requirements around snapshot. And while that can be achieved with the ID, it provides no context to the user.

**Review by hardillb — APPROVED** [review]

**Comment by Steve-Mcl** [comment]
@knolleary - I see Ben has approved the changes but please read and comment on my suggestion (above, dated 30th Jun)  before merging.

**Comment by knolleary** [comment]
@Steve-Mcl `FF_SNAPSHOT_NAME` added

**Comment by Steve-Mcl** [comment]
Thanks Nick. Reviewing now.

**Review by Steve-Mcl — APPROVED** [review]
👍

**Pull request merged**
