### PR TITLE
Add a label to a Stack

### LINKED ISSUE #915: Stack Label
### Epic/Story

As an admin I want to give a stack a user friendly label that is displayed to users when selecting a stack, 

### Description

We are meant to be a low-code, low technical entry point tool, but as part of creating a project, a user must select a stack:

Screenshot 2022-08-23 at 16 31 39

The no space formatting and lack of description looks too technical. We should have the option of a "nice"/formatted name for a given stack.

If I've selected a "Medium" project, I wouldn't expect to see `_Small`/`_Medium` at the end of the Stack name, simply `Node-RED v3.0.2` would suffice (with spacing).

### PR DESCRIPTION
**Pull request by hardillb**
Updates to use label if present, otherwise continue to use the name

fixes #915

### CODE REVIEW

**Comment by joepavitt** [comment]
looks fine, although I've noticed none of the E2E tests have run - any idea why that job may not have run?

**Comment by hardillb** [comment]
It's not showing any of the tests in the PR. It did initially and the normal tests all failed on a lint check, but disappeared when I pushed the fix.

Will work out how to kick them to run again.

**Comment by joepavitt** [comment]
@hardillb any idea if we can get them to run again? I've had a look, but can't see anything obvious

**Comment by hardillb** [comment]
I can't find a way to get them to run again on the latest version of the branch. I have run them and lint locally and they pass.

The only other option I can see is to close this PR and open a new one from the same branch

**Comment by joepavitt** [comment]
Risking it and merging to `main` feels scary to me, think we may need to do a new PR

**Comment by hardillb** [comment]
I'll close this and open a new one (it won't let me create a new one at the moment as far as I can see)

**Pull request closed without merging**
