### PR TITLE
Fix device seen status sometimes shows "never" even though has

### PR DESCRIPTION
**Pull request by Steve-Mcl**
## Description

Device seen "friendly" text would sometimes show "never" even though just moments ago it said "xx seconds ago"
There are several places in the UI code where a timestamp retrieved from DB is being compared to the browsers `Date.now()`.  Any differences in time between client and server will result in anomalous values.

This PR adds server side computed time device last seen as a milliseconds value. This is transmitted with the device view and can then be safely converted into human readable time period at the frontend.

## Related Issue(s)

#1723 

## Checklist

 - [x] I have read the [contribution guidelines](https://github.com/flowforge/flowforge/blob/main/CONTRIBUTING.md)
 - [ ] Suitable unit/system level tests have been added and they pass
 - [ ] Documentation has been updated
    - [ ] Upgrade instructions
    - [ ] Configuration details
    - [ ] Concepts
 - [ ] Changes `flowforge.yml`?
    - [ ] Issue/PR raised on `flowforge/helm` to update ConfigMap Template
    - [ ] Issue/PR raised on `flowforge/CloudProject` to update values for Staging/Production

## Labels

 - [-] Backport needed? -> add the `backport` label
 - [-] Includes a DB migration? -> add the `area:migration` label

### CODE REVIEW

**Review by joepavitt — APPROVED** [review]

**Comment by joepavitt** [comment]
Looks good to me @Steve-Mcl

**Comment by Steve-Mcl** [comment]
Thanks @joepavitt will get test written later today and re-request for you to check + merge.

**Comment by Steve-Mcl** [comment]
@joepavitt updated test to ensure new property is present.

Good to go (once tests complete)

**Comment by Steve-Mcl** [comment]
PG test fails were (it seems) due to GH actions not the code.

3rd time was the charm

Ready for review.

**Review by joepavitt — APPROVED** [review]

**Pull request merged**
