### PR TITLE
Include role in Team Invitation

### PR DESCRIPTION
**Pull request by knolleary**
Part of #1005 

This adds the ability to select the role of a user when inviting them - rather than default to Member.

This requires adding a column to the invitation table to store the role info.

Also updates the various views to include the role name in the UI.

### CODE REVIEW

**Review by hardillb — APPROVED** [review]

**Comment by hardillb** [comment]
The code reads ok, but the failure in the sqlite test implies that `Roles` is undefined which looks to be set right.

**Comment by hardillb** [comment]
Test also fails locally for me, so not some GitHub strangeness

**Comment by hardillb** [comment]
`RoleNames` is there, just `Roles` is empty which is strange

**Comment by knolleary** [comment]
Fix pushed.

Looks like vitest cannot do the alias importing like webpack can. I found the test was already working around that limitation by having a hardcoded copy of the roles data. But that meant it was old data - so I've changed it to load the real data properly.

**Comment by hardillb** [comment]
Will merge once tests have finished

**Pull request merged**
