### PR TITLE
Notifications

### PR DESCRIPTION
**Pull request by joepavitt**
Dependant upon #713 

https://user-images.githubusercontent.com/99246719/175071556-817a412b-effa-40ad-a589-0fc4a1915eb3.mov

### CODE REVIEW

**Comment by knolleary** [comment]
Having merged #748 there's a conflict here. Can you resolve?

**Comment by knolleary** [comment]
The screen recording shows notifications on pending team invites, but there are lots of commits adding alerts to lots of places as well - so is this a continuation of the work in #713, plus some new stuff on notifications?

**Comment by joepavitt** [comment]
> The screen recording shows notifications on pending team invites, but there are lots of commits adding alerts to lots of places as well - so is this a continuation of the work in #713, plus some new stuff on notifications?

@knolleary That's odd, it's included all of the changes in #713 in this PR too, even though they _shouldn't_ be a diff from `main` given that's been merged now. This branch was created as a branch of #713 as it was dependent upon it.

**Comment by joepavitt** [comment]
@knolleary sorted

**Review by knolleary — APPROVED** [review]

**Comment by knolleary** [comment]
Looks good.

As with #713, we need to capture how to use this somewhere/somehow.

**Pull request merged**
