### PR TITLE
Frontend for device owned snapshots

### PR DESCRIPTION
**Pull request by Steve-Mcl**
## Description

~NOTE: This is very much WIP.  Not to be merged until TODOs are addressed.~
Published for visibility and for progress to be made while I am tasked with other work.

* create a device snapshot
* list device owned snapshots
* delete a device owned snapshot
* list application owned snapshots (see `frontend/src/api/application.js` -> `getSnapshots`)

UPDATE 
* New Dev Mode toggle added
* New Developer Mode TAB

TODO:
* ~rework device list to be more like figma prepared by @joepavitt  - progressed~ 
   * update 25-09-2023. Joe progressed elements he wanted in this release.
* ~Add "Snapshots" table for Application @joepavitt~ - done
* ~show device ownership below breadcrumb~ - done
* ~replace developer mode button with new toggle~ done
* ~consolidate the SnapshotCreate dialogs~
   * `frontend/src/pages/device/dialogs/SnapshotCreateDialog.vue`
   * ~`frontend/src/pages/device/Snapshots/dialogs/SnapshotCreateDialog.vue`~ done, now uses one above
   * `frontend/src/pages/instance/Snapshots/dialogs/SnapshotCreateDialog.vue`
* ~remove kebab if no menu actions (instance snapshots on the device snapshots view should have no actions)~
   * follow up issue raised (see related issues beow)
* ~manual testing~
   * update 25-09-2023 - complete
* ~e2e tests~
   * UPDATE 26-09-2023: A branch based off this is currently under development for e2e

RELATED ISSUES:
* #2770 
* #2774 
* https://github.com/flowforge/flowforge/issues/2827

Optional (or part3 PR):
* ~documentation~ 
   * UPDATE 26-09-2023: DONE

## Related Issue(s)

#2609 

## Checklist

 - [x] I have read the [contribution guidelines](https://github.com/flowforge/flowforge/blob/main/CONTRIBUTING.md)
 - [ ] Suitable unit/system level tests have been added and they pass 
 - [x] Documentation has been updated
    - [ ] Upgrade instructions
    - [ ] Configuration details
    - [x] Concepts
 - [ ] Changes `flowforge.yml`?
    - [ ] Issue/PR raised on `flowforge/helm` to update ConfigMap Template
    - [ ] Issue/PR raised on `flowforge/CloudProject` to update values for Staging/Production

## Labels

 - [ ] Backport needed? -> add the `backport` label
 - [ ] Includes a DB migration? -> add the `area:migration` label

### CODE REVIEW

**Comment by Steve-Mcl** [comment]
@joepavitt, as discussed this weeks work pushed and the 1st post updated to reflect outstanding work and related issues.

**Comment by joepavitt** [comment]
I think I've caught everything:

https://github.com/flowforge/flowforge/assets/99246719/0f208fad-1a12-4edb-85db-c71fb930ad5b

Haven't gone for _full_ Developer Mode tab implementation for now, iteration, iteration, iteration.

This does add a new (useful) component called `InfoCard`, which we should (later) also utilise on the Instance page, as it prevents the need for copied pasted tailwind classes everywhere.

You'll notice that my Editor doesn't actually load at the end, but that's linked to https://github.com/flowforge/flowforge-device-agent/issues/173 which is still affecting my device-agent, although I would like @Steve-Mcl to double check on his machine that he _can_ access the Editor with the changes introduced here. The only errors I see are Node-RED side, so there shouldn't be any influence from my changes here.

**Comment by Steve-Mcl** [comment]
@joepavitt tested UI tweaks & tested device access following completion of https://github.com/flowforge/flowforge-device-agent/issues/173 - OK

One bug remains...
* Add a device
* Set device credentials
* Try to assign device to application - get error about not knowing the agent version
* Refresh page 
* Try to assign device to application - OK

**Comment by Steve-Mcl** [comment]
> I think the short term fix is to instruct user to "refresh page" because this goes deep into the overall paging of data for device list.

Resolved in [ad35325](https://github.com/flowforge/flowforge/pull/2750/commits/ad35325d0c5e8d3305e2e60b9aa29c37c1190332)


https://github.com/flowforge/flowforge/assets/44235289/0526b8ce-c0a5-48e4-af9a-b1530cbb4277




This is MVP - a better solution _might_ be possible but it is primarily an async timing issue (device config assignment is totally async to the forge web app)

**Comment by Steve-Mcl** [comment]
Switching back to draft
 - docs not updated (must do)
 - no e2e tests (stretch)

**Comment by joepavitt** [comment]
What wasn't intentionally added - it needs removing, that's fine.

**Review by knolleary — APPROVED** [review]

**Pull request merged**
