### PR TITLE
Add Viewer role

### PR DESCRIPTION
**Pull request by knolleary**
Adds a Viewer role to the platform.

They are full members of a team, but with read-only access to everything.

---

Remaining work:

 - [ ] tests around api access. Not sure how extensive to make it yet as `needsPermission` does all the heavy lifting
 - [ ] doc updates
 - [x] give user read-only access to the editor

### CODE REVIEW

**Comment by knolleary** [comment]
@hardillb I've marked this ready for review, but it isn't ready to merge yet. There will be some doc updates to follow - but wanted to give you the go ahead to start looking at the code. You'll be glad to hear, despite this requiring changes in the oauth flows, they are actually pretty limited in nature.

There will be a companion PR in the `nr-auth` repo shortly.

**Comment by hardillb** [comment]
@knolleary OK, will look after lunch

**Review by hardillb — APPROVED** [review]

**Comment by hardillb** [comment]
@knolleary Are you going to add the tests with the doc? Assuming so, happy to merge this

**Comment by knolleary** [comment]
Yes - the tests will be more around the invitation workflow that is coming in a later pr

**Pull request merged**
