### PR TITLE
Multiple Instances: Polish Tasks

### LINKED ISSUE #1950: Add application to devices API endpoint (as well as instance)
Currently the devices table doesn't show the application for a device.

It needs to be added to API and the front-end

### PR DESCRIPTION
**Pull request by Pezmc**
## Description

- Fixes UI of application name when deleting
- Prevents opening editor also navigating to another page
- Adds application to devices table

Screenshot 2023-04-12 at 18 16 36
Screenshot 2023-04-12 at 18 16 31
Screenshot 2023-04-12 at 18 16 20

## Related Issue(s)

Fixes #1950, part of #1914

## Checklist

 - [ ] I have read the [contribution guidelines](https://github.com/flowforge/flowforge/blob/main/CONTRIBUTING.md)
 - [ ] Suitable unit/system level tests have been added and they pass
 - [ ] Documentation has been updated
    - [ ] Upgrade instructions
    - [ ] Configuration details
    - [ ] Concepts
 - [ ] Changes `flowforge.yml`?
    - [ ] Issue/PR raised on `flowforge/helm` to update ConfigMap Template
    - [ ] Issue/PR raised on `flowforge/CloudProject` to update values for Staging/Production

## Labels

 - [ ] Backport needed? -> add the `backport` label
 - [ ] Includes a DB migration? -> add the `area:migration` label

### CODE REVIEW

**Review by joepavitt — APPROVED** [review]
Awaiting tests to run before merging, but all looks good, thanks Pez.

**Comment by Steve-Mcl** [comment]
Assuming the "Application" and "Instance" column entries are clickable, should we not indicate these are hyperlinks (blue text perhaps)?

At first glance, I have no idea I can click these.

**Comment by joepavitt** [comment]
> Assuming the "Application" and "Instance" column entries are clickable, should we not indicate these are hyperlinks (blue text perhaps)?

Appreciate the feedback Steve, having every application/instance name as blue text would be a little overwhelming with the highlighting of clickable things imo, but I do agree with your point. I don't want to rush in something for tomorrow, so will have a think about alternatives

**Comment by Steve-Mcl** [comment]
Upon driving latest staging env, I note that it is now a wee bit more difficult to delete an instance,

Prior to these changes, the `application-name-to-delete` was on its own line and could simply be triple clicked to highlight the full thing.  

Now I have to highlight with mouse :( (and waste many valuable milliseconds!)


Before:
chrome_Tdzy5SyMq3

After:
chrome_48CE2Bgkig


---

_its the little things 😄_

**Comment by Pezmc** [comment]
I think one could argue that it being slightly inconvenient is part of the design, and a "normal user" isn't going to be deleting a bunch of instances at once. Perhaps we could make the text click to copy though.

**Comment by Steve-Mcl** [comment]
> click to copy

Even betterer

**Pull request merged**
