### PR TITLE
Ensure labels for checkbox + radio are on same line

### LINKED ISSUE #1246: Label for Checkbox not displayed in-line
### Current Behavior

Noticed during Developer Demo

chrome_9E8svXReyL

In startup screen, the checkbox label is being indiscriminately set to `display:block` due to `.ff-layout--box--content label` CSS

### Expected Behavior

Label should be inline with check

### Steps To Reproduce

Start new FF instance & follow installer to Step 3

### Environment

- FlowForge version: 1.0.3

### PR DESCRIPTION
**Pull request by Steve-Mcl**
fixes #1246

### CODE REVIEW

**Comment by Steve-Mcl** [comment]
### Before
image


### After
image

**Comment by joepavitt** [comment]
Thanks @knolleary definitely want to check this through myself tomorrow

**Comment by joepavitt** [comment]
cross-posting from: https://github.com/flowforge/flowforge/issues/1246#issuecomment-1323502462

> Screenshot 2022-11-22 at 11 08 10
> 
> Just checked the `1133-form-row` branch for https://github.com/flowforge/flowforge/pull/1201 and it's okay there as I suspected it would be, as that re-writes the `checkbox` form row structure. Will wait for that to get merged and verify in `main`, but this issue should get resolved there.

**Comment by joepavitt** [comment]
verified that this PR is not longer required as #1246 was fixed in #1201

**Pull request closed without merging**
