### PR TITLE
Add configurable banner on Create Account page (rework)

### PR DESCRIPTION
**Pull request by knolleary**
## Description

This is an alternative approach (compared with #1589)  for how we can inject custom text into the Create Account page.

This takes a slightly broader approach and considers that we may want to introduce other bits of customisable text in the future.

Whilst the immediate need is related to billing, and my original suggestion was to put this under the billing config, in hindsight there is nothing inherently related to billing in wanting to add text to the create account page.

This proposes we add a new `branding` section in `flowforge.yml` under which we can organise any bits of customisable text.

For #1581, this PR adds support for the following:

```yaml
branding:
  account:
    signUpTopBanner: Free donuts for all
```

The entire `branding` object is passed to the UI via the `/settings` object. It currently only includes it in the unauthenticated request to `/settings` (as we only need it for the create user page), but a future iteration will want to make that smarter. We may even want to move it to a separate api end point to load these customisations... but that's for another day.

The choice of `signUpTopBanner` was based on the discussion in https://github.com/flowforge/website/issues/339 where I can see us wanting `signUpSideBanner` fairly soon...

## Related Issue(s)

 - #1589  

## Checklist

 - [x] I have read the [contribution guidelines](https://github.com/flowforge/flowforge/blob/main/CONTRIBUTING.md)
 - [-] Suitable unit/system level tests have been added and they pass
 - [-] Documentation has been updated
    - [ ] Upgrade instructions
    - [ ] Configuration details
    - [ ] Concepts

## Labels

 - [-] Backport needed? -> add the `backport` label
 - [-] Includes a DB migration? -> add the `area:migration` label

### CODE REVIEW

**Comment by joepavitt** [comment]
flagging for @hardillb as this'll require helm chart changes

**Comment by joepavitt** [comment]
Is the nesting inside `account` necessary? Feels like over-engineering a tad for our use case atm? `branding.signUpTopBanner` is still clear enough as to it's target content?

**Comment by joepavitt** [comment]
Tests failing atm - fix pending in https://github.com/flowforge/flowforge/pull/1592

**Comment by knolleary** [comment]
> Is the nesting inside account necessary? Feels like over-engineering a tad for our use case atm?

I was trying to apply a little forethought on were this would go and we may appreciate a little organisation from the start, rather than have to move things around later.

**Pull request merged**
