### PR TITLE
show proj suspend/delete dialog direct from menu

### LINKED ISSUE #1025: Suspending projects from actions menu should goto confirmation dialog
### Current Behavior

When clicking "suspend" in the actions list of the project overview it redirects you to the settings page. On that page the user needs to find the suspend button again, and then gets a pop up to suspend the actual project.

### Expected Behavior

When clicking "suspend" in the actions list of the project overview it shows the confirmation dialog immediatly

### Steps To Reproduce

_No response_

### Environment

- FlowForge version: 0.10

### PR DESCRIPTION
**Pull request by Steve-Mcl**
fixes #1025 

### Before
Clicking `Suspend` or `Delete` on the `Action` menu would take to you to another page.

### After
chrome_lA3izl0yG1

### CODE REVIEW

**Comment by joepavitt** [comment]
Noticing you're recording this from the "Settings > Danger" page already - what happens if you're on the general Overview page for a project for example?

**Comment by joepavitt** [comment]
The Cypress tests will be failing due to my relatively vague element selectors, so it'll be finding both your new "Delete" action and whatever action was there prior and trying to click both (unsuccessfully). Easily fixed.

**Comment by Steve-Mcl** [comment]
> Noticing you're recording this from the "Settings > Danger" page already - what happens if you're on the general Overview page for a project for example

Well spotted :) 

It is the same on all pages with the Action button 

chrome_j9mr3QcsbZ

> The Cypress tests will be failing due to my relatively vague element selectors, so it'll be finding both your new "Delete" action and whatever action was there prior and trying to click both (unsuccessfully). Easily fixed.

I had a feeling it would - I cheekily published to get the results of the E2E due to state of local dev ATM - just wished we had slack integration with cypress results to send us pics/vids - something like https://github.com/marketplace/actions/cypress-screenshot-video-upload-to-slack

**Comment by joepavitt** [comment]
> something like https://github.com/marketplace/actions/cypress-screenshot-video-upload-to-slack

I'd definitely support adding an `fe-e2e-tests` channel to Slack and having this report there.

**Comment by Steve-Mcl** [comment]
@joepavitt ready for review.

NOTE: I used `data-el="platform-dialog"` as `data-el="dialog"` was potentially too generic?

**Review by joepavitt — APPROVED** [review]

**Pull request merged**
