### PR TITLE
docs: Update RBAC table

### PR DESCRIPTION
**Pull request by Steve-Mcl**
prep for #854, #858

### CODE REVIEW

**Comment by Steve-Mcl** [comment]
@sammachin please add additional reviewers if you believe them necessary.

**Comment by sammachin** [comment]
Thanks @Steve-Mcl this is really useful, just to confirm this is the current state as of 0.8.0?
In which case I think we should merge this as is and then iterate on where we feel changes need to be made on a case by case basis.

**Comment by Steve-Mcl** [comment]
@sammachin 

> just to confirm this is the current state as of 0.8.0?

Kind of - let me try to clarify

It is mostly`*` the operational state as found when operating buttons / navigating while logged in as a "non owner".  The visual/UI state is often incorrect as of 0.8. 
Example - in `#843` there are [6 places](https://github.com/flowforge/flowforge/issues/843#issuecomment-1207855648) (there are more) where a button/menu/action is visible/clickable but should (probably) not be.  Therefor this PR aims to determine correct RBACs

So, ideally, I need eyes on this to double check my assumptions/findings/sensible guesses as to what it should be both from a front end and back end perspective.

Perhaps we need to add Nick's or Ben's eyes too as they developed many of the features highlighted?


<br>

<small>`*` some things like "viewing environment variables" are the desired condition following discussion with Nick</small>

**Comment by sammachin** [comment]
Few items to change, mostly giving members more access, 
In principle a member should be able to do anything to build and deploy a project to a device but they can't do anything chargeable, destructive, or that changes the membership of the team (other than leave the team themselves)

A Member should be able to 
Snapshots
	Create Snapshot
	Rollback
Devices
	Edit Environment Variables
	Device Row Menu (but not delete device)
	Device Settings
		Edit Environment Variables
Settings
	Edit Environment Variables

They should also be able to assign a device from the team to a project, can't see where that is in the list?

**Review by sammachin — CHANGES_REQUESTED** [review]
as detailed in comments

**Comment by Steve-Mcl** [comment]
> as detailed in comments

Changes applied in [a153cba](https://github.com/flowforge/flowforge/pull/865/commits/a153cba898a210d5e2fbfd395ba0277dd13af688)

**Pull request merged**
