### PR TITLE
Fix dropdown z-index and overflow issue

### LINKED ISSUE #1305: dropdown only shows one item (have to scroll for others)
### Current Behavior

chrome_av0OQhQ1rd

### Expected Behavior

* no scrolling.

### Steps To Reproduce

on team devices, click the kebab menu then "add to project"

### Environment

- FlowForge version: 1.1.0-git

- Platform/OS: Win 11
- Browser: Chrome

### PR DESCRIPTION
**Pull request by Pezmc**
Fixes #1305. This is a quick fix, the wider issue is in https://github.com/flowforge/forge-ui-components/issues/105.

### CODE REVIEW

**Review by Steve-Mcl — APPROVED** [review]
Looks sane. Is Joe around today to check off this temporary fixup?

**Comment by knolleary** [comment]
@Steve-Mcl no. We need to verify this without him.

**Comment by Steve-Mcl** [comment]
2 mins, I'll pull locally and do quick visual test

**Comment by Steve-Mcl** [comment]
Working now. Will merge once e2e tests complete.

**Review by Steve-Mcl — APPROVED** [review]
2nd time is the charm

**Pull request merged**
