### PR TITLE
Permit admin to manually verify users email

### LINKED ISSUE #692: Manually Verify User Email
### Epic

_No response_

### Description

**As a:** admin

**I want to:** be able to mark a users email as verified 

**So that:** I can confirm a user that is having trouble with the verification emails

### Which customers would this be availble to

- [X] All Users, (CE)
- [ ] Specific Project Types (EE)
- [ ] Specific Team Tiers (EE)
- [ ] Other (See comments)

### Acceptance Criteria

- [ ] Verify Email button on edit user modal where email is not verified.

### PR DESCRIPTION
**Pull request by Steve-Mcl**
fixes #692

## PR
* Adds "☑️ Email Verified" checkbox (protected by an 🔒unlock button) to the "Edit Users" form: to permit an admin to verify a users email on their behalf
* Aligns items in the "Edit Users" form (was getting pretty ugly with all the unlock buttons misaligned)
* Adds tests to `routes\api\user_spec.js` and `routes\api\users_spec.js` to cover API change

## Functional changes
* `routes\api\shared\users.js` - update email_verified DB field 

## UI changes
* `frontend\src\pages\admin\Users\dialogs\AdminUserEditDialog.vue` - adds new form row for email_verified DB field 
* `frontend\src\components\FormRow.vue` - updated to permit optional class (to attain symmetrical layout on AdminUserEditDialog.vue)
chrome_A9IqqjL0o7

### **User API** (`routes\api\user_spec.js`)
* User settings
    * member user can modify non admin settings (name, email, username)
    * member user cannot modify admin settings (email_verified, admin)
    * Verify Email
        * user cannot manually verify own email
    #### Results...
    ```
    User API
        User settings
        √ returns 401 on /user if not logged in (186ms)
        √ return user info for logged in user (78ms)
        √ member user can modify non admin settings (name, email, username) (102ms)
        √ member user cannot modify admin settings (email_verified, admin) (73ms)
        Unverified Email
            √ return user info for unverified_email user (71ms)
            √ cannot access other parts of api (80ms)
        Verify Email
            √ user cannot manually verify own email (73ms)
        Password Expired
            √ return user info for password_expired user (71ms)
            √ password_expired user can change password (210ms)
            √ cannot access other parts of api (74ms)
    10 passing (9s)
    ```

### **Users API**  (`routes\api\users_spec.js`)
* Update user settings
    * Modify a user
        * admin can manually verify email
        * team owner can not manually verify email
        * member can not manually verify own email
        * team member can not manually verify a users
        * other team owner can not manually verify a
        * anonymous can not manually verify a users email

    #### Results...
    ```
    Users API
        Update user settings
        Default Team
            √ can set defaultTeam to a team the user is in
            √ cannot set defaultTeam to a team the user is not in
            √ cannot set defaultTeam to null
            √ cannot set defaultTeam to invalid value
        Modify a user
            √ admin can manually verify email
            √ team owner can not manually verify email
            √ member can not manually verify own email
            √ team member can not manually verify a users email
            √ other team owner can not manually verify a users email
            √ anonymous can not manually verify a users email
        Delete a user
        √ Cannot delete an admin user
        √ Admin cannot delete themselves
        √ Cannot delete a team owner
        √ Non-admin cannot delete user
        √ A deleted user can no longer access the API with an existing session token
        √ Deleting a user removes pending invites for them (117ms)
        √ Deleting a user removes them from all teams they are in (51ms)
    17 passing (21s)
    ```

## Local checks
* all tests pass locally
* all forms using component `FormRow` unaffected by modification for layout/alignment
* parent form (`admin/users/general`) table of users updates when email verification is updated

### CODE REVIEW

**Review by joepavitt — APPROVED** [review]

**Comment by sammachin** [comment]
Does this now work the same way as the administrator checkbox, in that if I go to edit a user that is already verified it will show the check box?
Does this mean that its possible to unverify a user by turning the status off? What is the experience there?

**Comment by joepavitt** [comment]
@Steve-Mcl to Sam's point - I believe it is possible now to unverify a user?

**Comment by Steve-Mcl** [comment]
Yes, it means it is possible to "unverify" - I used a checkbox so that the state of `email_verified` could be know to the admin viewing. 

My logic for this is - should an admin actually make a mistake by manually verifying the wrong user or wrong Email addres (unheard of ;) ) he can simply "un-verify" - no harm no foul.

Of course, if this is an issue, I can change the UI/logic as required.

**Comment by joepavitt** [comment]
> - no harm no foul.

+1

**Comment by sammachin** [comment]
Ok that makes sense, yes its useful to keep.

I assume if you unverify a user that doesn't trigger a new verification email? But if they login they should be shown the "you need to verify" screen and from that can request that the email is (re)sent.

**Pull request merged**
