### PR TITLE
Add application description to header of application summary box

### PR DESCRIPTION
**Pull request by Steve-Mcl**
## Description

Add description to applications.  Ensure text does not overflow when sized. Permit user setting of description.

### Demo

https://github.com/flowforge/flowforge/assets/44235289/b1c06ed9-d83c-4b00-823c-3ac776e0fa66

### Commits:
[db migration - description column to Applications](https://github.com/flowforge/flowforge/commit/fc72d4f1f7488897519f88356349e3839e79f356)

[update db Application model - add description col](https://github.com/flowforge/flowforge/commit/d1ee6971766ec1a2b68b699901b5a871d419ff5b)

[update db view for new column](https://github.com/flowforge/flowforge/commit/27f792201cab09c3de4972928c61e324588bd2e0)

[update backend api for new description field](https://github.com/flowforge/flowforge/commit/56c1d7cf60897732ce17d5426282318b9fee6b22)

[add description to client API for updating appl'n](https://github.com/flowforge/flowforge/commit/2067d6b7b1c4a4f3e338a7d23f16b7da9cb2d5fc)

[front end CRUD for new description field](https://github.com/flowforge/flowforge/commit/3ec56641516cb634b13c4a34ed37bc6e2c4d5af6)

[update unit tests for new description field](https://github.com/flowforge/flowforge/commit/ad78afb1368abab1cfb76c99d0168d80a956620c)

[update frontend tests for description co](https://github.com/flowforge/flowforge/commit/28c95e3fa1e49ce5a6af811337876db34c9596a1)

### Additional
Docs were reviewed and no immediate changes were necessary BUT there was outdated info present in the Application Concepts. As these were (tenuously) related, I have updated them as part of this PR.
_+ 1 typo fixed._

## Related Issue(s)

#2279 

## Checklist

 - [x] I have read the [contribution guidelines](https://github.com/flowforge/flowforge/blob/main/CONTRIBUTING.md)
 - [x] Suitable unit/system level tests have been added and they pass 
 - [x] Documentation has been updated
    - [ ] Upgrade instructions
    - [ ] Configuration details
    - [x] Concepts
 - [ ] Changes `flowforge.yml`?
    - [ ] Issue/PR raised on `flowforge/helm` to update ConfigMap Template
    - [ ] Issue/PR raised on `flowforge/CloudProject` to update values for Staging/Production

## Labels

 - [ ] Backport needed? -> add the `backport` label
 - [x] Includes a DB migration? -> add the `area:migration` label

### CODE REVIEW

**Comment by Steve-Mcl** [comment]
@MarianRaphael - backport flag required for Thursday release?

**Comment by Steve-Mcl** [comment]
Fixed UI tests by adding missed functionality (inputting / displaying application description on application / instance creation) in [4b14b58](https://github.com/flowforge/flowforge/pull/2596/commits/4b14b582d822bd8176fbf6221565d365223cd59b)

**Comment by Steve-Mcl** [comment]
@joepavitt @knolleary gentle nudge :) 

Marian has added backport label signifying this will be in Thursday release - needs to be tested on staging etc.

**Review by joepavitt — APPROVED** [review]
Approved from front-end

**Review by knolleary — APPROVED** [review]

**Pull request merged**
