### PR TITLE
Implement FormRow.focus and fix focus throughout the app

### PR DESCRIPTION
**Pull request by Pezmc**
Fixes https://github.com/flowforge/flowforge/issues/1081, should be revisited again if https://github.com/flowforge/forge-ui-components/issues/61 is implemented as lots of the usage is simply focusing on first load.

**Blocked** by https://github.com/flowforge/forge-ui-components/pull/62, which must be merged first. It implements the focus method.

**Do not merge** until a new release is cut.

### CODE REVIEW

**Review by Steve-Mcl — COMMENTED** [review]
It looks good Pez.  One question though, why is the license E2E test bundled with this PR?

**Comment by Pezmc** [comment]
I wanted to add test coverage of the focus changes on the license page, but it had no test coverage yet so had to write a full test from scratch

**Comment by Steve-Mcl** [comment]
OK, understood. 

It is however failing "can set license" with `this.$refs.input?.focus is not a function` 

```
FlowForge platform admin users
(node:1778) [FSTDEP012] FastifyDeprecation: Request#context property access is deprecated. Please use "Request#routeConfig" or "Request#routeSchema" instead for accessing Route settings. The "Request#context" will be removed in `fastify@5`.
    ✓ can login in (4164ms)
    ✓ can view (and click) the "Admin Settings" in user options (2551ms)
    ✓ can navigate to Admin Settings directly (2222ms)
    1) can set license
    ✓ can view projects from teams they're not a member of (4699ms)
    ✓ can view devices from teams they're not a member of (4694ms)

  FlowForge platform non-admin users
    ✓ can login in (1871ms)
    ✓ cannot view the "Admin Settings" in user options (1866ms)
    ✓ cannot navigate to Admin Settings directly, and should be redirected (1915ms)


  8 passing (28s)
  1 failing

  1) FlowForge platform admin users
       can set license:
     TypeError: The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.
```



And also failing "prevents a user logging in with incorrect credentials" - though I am uncertain if that is due to your changes?

```
  FlowForge
    ✓ successfully loads (1123ms)
    1) prevents a user logging in with incorrect credentials
    ✓ requires a password (1300ms)
    ✓ allows a user to login (2145ms)
    ✓ prevent long password (15197ms)


  4 passing (26s)
  1 failing

  1) FlowForge
       prevents a user logging in with incorrect credentials:
     AssertionError: Timed out retrying after 4000ms: expected '[ <label.ff-error-inline>, 2 more... ]' to be 'visible'

This element `[ <label.ff-error-inline>, 2 more... ]` is not visible because it has an effective width and height of: `272 x 0` pixels.
      at Context.eval (http://localhost:3000/__cypress/tests?p=test/e2e/frontend/cypress/tests/auth.spec.js:113:32)
```

**Comment by Steve-Mcl** [comment]
I just spotted the comment...

> Blocked by https://github.com/flowforge/forge-ui-components/pull/62, which must be merged first. It implements the focus method.

Is that the reason for both test failures?

**Comment by Steve-Mcl** [comment]
### NOTE TO SELF...
https://github.com/flowforge/forge-ui-components/pull/62 has now been merged.

### Once next version of `forge-ui-components` is published to NPM...
* update package.json dependency version to match
* ensure tests pass
* merge

**Pull request merged**
