### PR TITLE
Pipelines: Server side deployment state tracking

### PR DESCRIPTION
**Pull request by Pezmc**
## Description

Split into two parts:

 - Refactor the existing state tracking to work based on stage deploy state (deduced from instance state)
 - Move storage of instance deploy state server side

Key advantages:
 - State persists across page reloads
 - Deploy complete alert works regardless of what starting state the instance was in

https://github.com/flowforge/flowforge/assets/507155/5a8ac2bc-0311-467e-9674-f1ac0dab698b

## Related Issue(s)

N/a

## Checklist

 - [x] I have read the [contribution guidelines](https://github.com/flowforge/flowforge/blob/main/CONTRIBUTING.md)
 - [-] Suitable unit/system level tests have been added and they pass - Not really clear how to test this. Page already has E2E coverage.
 - [ ] Documentation has been updated
    - [ ] Upgrade instructions
    - [ ] Configuration details
    - [ ] Concepts
 - [ ] Changes `flowforge.yml`?
    - [ ] Issue/PR raised on `flowforge/helm` to update ConfigMap Template
    - [ ] Issue/PR raised on `flowforge/CloudProject` to update values for Staging/Production

## Labels

 - [ ] Backport needed? -> add the `backport` label
 - [ ] Includes a DB migration? -> add the `area:migration` label

### CODE REVIEW

**Comment by Pezmc** [comment]
@joepavitt Would appreciate some click testing from you to verify the UI still behaves as you expect!

**Comment by joepavitt** [comment]
Didn't work for existing pipeline I had, but creating a new pipeline worked at first whilst in "installing", but my local seems to be getting stuck in "starting" again.

Also notice that the polling doesn't seem to be enabled upon refresh? If I click "play" and then immediately refresh, has some instances where the target stage stay locked in "Installing" until I refreshed again.

**Comment by Pezmc** [comment]
@joepavitt Looks like I hadn't pushed my latest 😊, will do a sanity check and retag you! Sorry for wasted time!

**Comment by Pezmc** [comment]
@joepavitt Ready for a re-review

**Review by knolleary — APPROVED** [review]
Done some clicking around, all appears functional. Refreshing the page, getting the inflight state updated properly. All good.

**Comment by knolleary** [comment]
The only thing that caught me out was what lead me to raise #2332 as I thought things weren't updating properly. But that's (quite literally) a separate issue.

**Comment by joepavitt** [comment]
Have managed to get my local up and running again for a couple of days blocked. Will try and get to this review this afternoon as I'm trying to round up the Dashboard work. If Nick is happy though, feel free to proceed @Pezmc

**Review by joepavitt — APPROVED** [review]

**Pull request merged**
