### PR TITLE
Move linux service start instructions

### PR DESCRIPTION
**Pull request by hardillb**
setting up the service is a question asked by the linux install.sh which is why it's not mentioned anywhere else in the docs

### CODE REVIEW

**Comment by hardillb** [comment]
@Steve-Mcl can I merge this?

**Review by Steve-Mcl — CHANGES_REQUESTED** [review]
Ben, I thought we were to change the wording as per your screenshot...

image

**Comment by hardillb** [comment]
Sorry, thought I'd already pushed it, check now please

**Review by Steve-Mcl — APPROVED** [review]
Much betterer 👍

**Pull request merged**
