### PR TITLE
Add functions & framework for exact audit logging

### PR DESCRIPTION
**Pull request by Steve-Mcl**
part of #1183

Merge after #1225, #1226, #1227, #1228

This part of the work introduces...
* A framework encapsulating all current audit log calls so as to promote known structure that adheres to #1183

NOTE: This PR is simply framework and is therefore passive (doesnt yet change the audit logging). Further PRs will utelise the functions this framework introduces.

### CODE REVIEW

**Review by Steve-Mcl — COMMENTED** [review]
All good Joe - happy to merge

**Comment by Steve-Mcl** [comment]
NP. let me know when done & I will review ASAP.

**Comment by joepavitt** [comment]
I also still need to ru through and test the other 4 PRs to merge into here before this one is ready

**Comment by joepavitt** [comment]
with changes about to be pushed, coverage from unit tests for this work is:

Screenshot 2022-11-17 at 12 28 11

**Comment by Steve-Mcl** [comment]
@knolleary Nick, what is the current status of this?  I see 1241 was merged.

Can this be merged to main or is there something I can do to get it there?

Ta

**Comment by Steve-Mcl** [comment]
@knolleary @joepavitt 

Ready for review (or merge)

#### Issues found and fixed by manual e2e...

1. 1 func call not renamed & therefore causing exception in route `put('/:teamId',`
3. Inconsistent results from userObject & triggerObject based on varying parameters & how the hashid/name is determined from the varying input (e.g. in `post('/account/reset_password/:token'`, the `token.ownerId` is a hashid not an id). Also, missing negative tests around this. Added extensive list of tests for both `userObject and triggerObject
4. Removed `hashid` prop from `projectObject` (project does not have a hashid) & updated tests


#### Events list & status...

forge/auditLog/__.js | Scope | Event | Success
-- | -- | -- | --
user.js | platform | account.register | OK
user.js | platform | account.logout | OK
user.js | platform | account.login | OK
user.js | platform | account.forgot-password | OK
user.js | platform | account.reset-password | OK
user.js | platform | account.verify.auto-create-team | OK
user.js | platform | account.verify.request-token | OK
user.js | platform | account.verify.verify-token | OK
user.js | platform | user.updated-password | OK
user.js | platform | user.updated-user | OK
user.js | platform | user.invitation.accepted | OK
user.js | platform | user.invitation.deleted | OK
user.js | platform | users.created-user | OK
user.js | platform | users.deleted-user | OK
user.js | platform | users.auto-created-team | OK
team.js | team | users.updated-user | OK
team.js | team | team.created | OK
team.js | team | team.deleted | OK
team.js | team | team.user.added | OK
team.js | team | team.user.removed | OK
team.js | team | team.user.invited | OK
team.js | team | team.user.uninvited | OK
team.js | team | team.user.invite.accepted | OK
team.js | team | team.user.invite.rejected | OK
team.js | team | team.user.role-changed | OK
team.js | team | team.settings.updated | OK
team.js | team | team.device.created | OK
team.js | team | team.device.deleted | OK
team.js | team | team.device.updated | OK
team.js | team | team.device.unassigned | OK
team.js | team | team.device.assigned | OK
team.js | team | team.device.credentials-generated | OK
team.js | team | project.duplicated | OK
team.js | team | project.created | OK
team.js | team | project.deleted | OK
team.js | team | billing.session.created | cant test locally
team.js | team | billing.session.completed | cant test locally
team.js | team | billing.subscription.deleted | OK
project.js | project | project.created | OK
project.js | project | project.deleted | OK
project.js | project | project.started | OK
project.js | project | project.stopped | Cant test from UI
project.js | project | project.restarted | OK
project.js | project | project.suspended | OK
project.js | project | project.flow-imported | OK
project.js | project | project.device.unassigned | OK
project.js | project | project.device.assigned | OK
project.js | project | project.stack.changed | OK
project.js | project | project.settings.updated | OK
project.js | project | project.snapshot.created | OK
project.js | project | project.snapshot.rolled-back | OK
project.js | project | project.snapshot.deleted | OK
project.js | project | project.snapshot.device-target-set | OK
platform.js | platform | platform.settings.updated | OK
platform.js | platform | platform.stack.created | OK
platform.js | platform | platform.stack.deleted | OK
platform.js | platform | platform.stack.updated | OK
platform.js | platform | platform.project-type.created | OK
platform.js | platform | platform.project-type.deleted | OK
platform.js | platform | platform.project-type.updated | OK
platform.js | platform | platform.license.applied | OK
platform.js | platform | platform.license.inspected | OK

**Pull request merged**
