### PR TITLE
Application Instances: Live statuses

### LINKED ISSUE #1911: Re-implement start/stop/destroy of instances on Application > Overview
This wasn't implemented in the first round of application model, it needs to be added.

### LINKED ISSUE #1919: Application  Overview: Live instance status

### PR DESCRIPTION
**Pull request by Pezmc**
## Description

- Adds start/resart/suspend/delete to the Application Overview
- Adds polling of instance status to Team > Applications, Application > Overview and Instance > Overview

## Related Issue(s)

Fixes #1911 
Fixes #1919

## Checklist

 - [x] I have read the [contribution guidelines](https://github.com/flowforge/flowforge/blob/main/CONTRIBUTING.md)
 - [ ] Suitable unit/system level tests have been added and they pass
 - [-] Documentation has been updated
    - [ ] Upgrade instructions
    - [ ] Configuration details
    - [ ] Concepts
 - [-] Changes `flowforge.yml`?
    - [ ] Issue/PR raised on `flowforge/helm` to update ConfigMap Template
    - [ ] Issue/PR raised on `flowforge/CloudProject` to update values for Staging/Production

## Labels

 - [ ] Backport needed? -> add the `backport` label
 - [ ] Includes a DB migration? -> add the `area:migration` label

### CODE REVIEW

**Comment by joepavitt** [comment]
State doesn't seem to refresh after "stopped" when doing a restart:

https://user-images.githubusercontent.com/99246719/230573963-9ace72b9-0854-4442-be44-d7e204b9782f.mov

**Comment by joepavitt** [comment]
We seem to get 3 different values for "last updated/deployed" depending on which screen we look at, which I'm guessing means a different API call?

## No Data:

This appears on the Team > Applications screen. Looking at the API responses for `/applications` and `/status`, we don't ever seem to return data that could populate here.

Screenshot 2023-04-07 at 10 12 50

## Last Deployed in Node-RED

This value aligns with when the "Deploy" button was last clicked inside Node-RED:

Screenshot 2023-04-07 at 10 12 41

## Last Edited

This seems to align with when there was _any_ change to the Instance itself, e.g. restarted/suspended?

Screenshot 2023-04-07 at 10 12 57

**Comment by joepavitt** [comment]
Just also raising recent test failure here as this looks like a strange one:

```
⎯⎯⎯⎯⎯⎯⎯ Failed Tests 1 ⎯⎯⎯⎯⎯⎯⎯

 FAIL  test/unit/frontend/utils/elapsedTime.spec.js > elapsedTime > compares relative to now if only a to date is passed
AssertionError: expected '30 minutes, 14 seconds' to be '30 minutes, 15 seconds' // Object.is equality
 ❯ test/unit/frontend/utils/elapsedTime.spec.js:58:35
     56|         soon.setSeconds(soon.getSeconds() + 15)
     57| 
     58|         expect(elapsedTime(soon)).toBe('30 minutes, 15 seconds')
       |                                   ^
     59|     })
     60| 

  - Expected   "30 minutes, 15 seconds"
  + Received   "30 minutes, 14 seconds"
```

**Comment by Pezmc** [comment]
Looks like the restarting issue isn't reproducible on the stub driver, am looking into it!

**Comment by Pezmc** [comment]
Let's split out the last updated issue separately so this PR can move forward since a bunch of the others depend on it!

**Comment by joepavitt** [comment]
Screenshot 2023-04-11 at 09 14 02

now seeing all of my instances in "Starting" state as returned by the API, despite them all actually having been started or suspended (showing as "unknown" in API response at Application level)

**Comment by joepavitt** [comment]
hmm, just went back to the overview again, and now they're all showing as "running" as they should have. Suspect this was a delay from restarting FlowForge? but it's still odd...

The "unknown" state is still an issue

**Comment by joepavitt** [comment]
Unfortunately, this has now completely broken status for Node-RED instances. Restarting gets them stuck in "starting"

**Comment by Pezmc** [comment]
Joe and I looked into this and confirmed most of the issues outlined above were only on his local (with the localfs driver). We're doing another round of click testing now.

**Review by joepavitt — APPROVED** [review]

**Pull request merged**
